services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=Password123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
        test: ["CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Password123", "-Q", "SELECT 1"]
        interval: 10s
        timeout: 5s
        retries: 5

  webapi:
    build:
      context: .
      dockerfile: Hospital.Presentation/Dockerfile
    image: hospital.presentation:1.0
    ports:
      - "5000:80"
    depends_on:
      - mssql
    environment:
      - ConnectionStrings__Default=Server=mssql;Database=Hospital;User Id=sa;Password=Password123;

  console:
    build:
      context: .
      dockerfile: Hospital.Console/Dockerfile
    image: hospital.console:1.0
    depends_on:
      - mssql
    stdin_open: true
    tty: true
    environment:
      - ConnectionStrings__Default=Server=mssql;Database=Hospital;User Id=sa;Password=Password123;

volumes:
  mssql_data: